### ISSUE TITLE
Unused PVCs remain after long periods of time

### ISSUE THREAD

**Issue by eengelking** [cdr/enterprise-helm#153]
When a user creates a workspace, it creates an associated PVC for the pod to use and store data.

In the use case we're seeing, a workspace has been abandoned or left unused for a long period of time.  As a result, the PVCs remain, detached, and incur cost within the cloud environment.

It would be useful if we could have a method to show old workspaces and have a method to perform maintenance on the old environments.  An additional useful tool would be to notify/alert users of old workspaces and/or provide a method to automatically remove workspaces that have been unused for 30 days, 90 days, etc.  This feature could be added to the Account Dormancy page.

**Comment by eengelking** [comment]
Example unattached PVCs over time:
![image](https://user-images.githubusercontent.com/1142070/134713790-792445d4-8f76-4603-9818-67f5cd798ebf.png)

**Comment by ericpaulsen** [comment]
Thanks for submitting @eengelking - I've logged this internally for our product team to review.
