### ISSUE TITLE
Workspace terminals can crash Kubernetes nodes or other pods

### ISSUE THREAD

**Issue by eengelking** [cdr/enterprise-helm#154]
It is possible to deploy a workspace pod and use that pod to fill up storage on the local node, which in turn can either crash the node and/or other pods running on that node, depending on how volumes are planned on deployment.

**Steps to re-create:**

Follow the instructions to deploy Coder using the EKS environment:
https://coder.com/docs/coder/v1.23/setup/kubernetes/aws

Once the environment is online:
1. SSH to Kubernetes nodes.
2. In the node(s), run `df -h` to show the current storage.  Note specifically the root `/` partition size.
3. In Coder, running on this cluster, launch a new workspace.
4. Open the Terminal in the workspace.
5. In the workspace terminal, run `df -h` to show current pod storage.  Note specifically the root `/` partition and `/etc/hosts` storage size.  These should reflect the same size as the root in step 2 above.
6. Take the available storage from step 5 and divide it by half.
7. In the workspace terminal, run the following command: `sudo fallocate -l <size> /testfile.img`<br />
**Note:** The `<size>` in the `fallocate` command should be determined from step 6.
8. In the workspace terminal, determine the file was created and meets the size set: `ls -lah /testfile.img`
9. In the workspace terminal, run `df -h` to show current pod storage.  The available space show now be half of what it was originally.
10. In the node terminal, run `df -h` to show current storage.  It should now be in half as well.

**What's happening:** By default, the `/var/lib/docker` directory is attached to the root volume.  As there's no storage limits on the pod when it is created, it has full access to the available storage of the volume containing the container, in this case the root directory of the host node.  

To help prevent crashing the host node, additional storage volume can be created and mapped to `/var/lib/docker`. However, this would not resolve the issue with the pod having full access to the volume to max it out.  This could potentially break existing pods or prevent new pods from being deployed on the node or nodes affected.

**Solution:** Since the pod uses a PVC for storage for the home directory, there is no need to allow directories outside of home to be wide open to use up available storage on the nodes.  Instead they should be limited to the total amount of storage by setting requests and limits for local ephemeral storage when creating the workspace pod.  The only way to break the node volumes from this point would be to create a significant number of workspaces and purposefully max out each root volume.

More details here:
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#setting-requests-and-limits-for-local-ephemeral-storage

It may be worthwhile to have a means to detect workspaces that are using storage outside of the home directory and stop them if a certain size is detected.

**Comment by ericpaulsen** [comment]
Thanks for submitting this @eengelking. I've logged this internally for our product team to review.
