### ISSUE TITLE
Database updates or failovers can break Coder

### ISSUE THREAD

**Issue by eengelking** [cdr/enterprise-helm#155]
When using a production database, running updates on the database could break Coder and prevent users from being able to use the service.

Example:
1. Create a highly available database.
2. Connect Coder to the database using the database cluster endpoint.
3. Perform a failover of the HA database, for example during a software update.

**What's happening**: From time to time during a database failover, Coder will maintain the connection to the database and will not release it once the failover has occurred, preventing access to the database.  The only way to solve this problem is to delete the `coderd` pods and wait for them to come back online.  

This is problematic, as a schedule maintenance may occur over the weekend and Coder may not release the database connection.  While the database update and/or testing may have worked as expected, anyone who would go to use Coder would find the service unavailable.

It would be beneficial if Coder would recognize when it can no longer read/write from a database, timeout the connection automatically, and retry the connection again.  If it cannot read the database after several attempts, it would log the behavior which can easily be captured and alerted on.

**Comment by ericpaulsen** [comment]
Thanks for submitting @eengelking. I've logged this internally for our product team to review.
